name: DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:

  security-sast:
    name: SAST + Linting + Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: pip install -r backend/requirements.txt

    # ---------- SAST ----------
    - name: Run Bandit (Python security scan)
      run: bandit -r backend -ll

    # ---------- Dependency Scan ----------
    - name: Run Safety (Dependency CVE scan)
      run: pip install safety && safety check -r backend/requirements.txt

    # ---------- Tests ----------
    - name: Run pytest
      run: pytest backend/tests --disable-warnings --maxfail=1


  security-image:
    name: Docker Build + Container Security
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t mercury-backend backend

    - name: Scan container with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'mercury-backend'
        severity: CRITICAL,HIGH
        exit-code: 1

  security-secrets:
    name: Secret Scanning
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Gitleaks
      uses: gitleaks/gitleaks-action@v2


  security-dast:
    name: DAST Scan (OWASP ZAP)
    runs-on: ubuntu-latest

    services:
      backend:
        build:
          context: ./backend
        ports:
          - 8000:8000

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: ZAP Baseline Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: "http://localhost:8000"
